robofit/arcor2

arcor2/server/project.py
It was not possible to open a project where AP had another AP as a parent.
=> OpenProject fixed

arcor2/server/objects_actions.py, arcor2/server/robot.py
Features were not found out properly when the method was defined in a predecessor.
=> ARServer: RobotMeta fixed

docker/fit-demo/README.md, docker/fit-demo/docker-compose.yml
ARCOR2_DATA_PATH was missing in compose file.
Outdated network name was fixed in README file
=> fix: fit-demo example fixes

pants.toml
Inter-repository dependencies (in generated setup.py) are now set to ~= insted of ==
=> build: new version of Pants

src/python/arcor2_kinali/object_types/kinali_robot.py
The exact assertion was:
`assert path[-2].node is within_node, (path[-2].node, within_node)`
=> fix(arcor2_kinali): removed comments causing AssertionError in horast

pants, pants.toml
- It now internally uses Python 3.6.
- `use_coverage` temp. switched off due to problems with integration tests.
=> build: last version of Pants

src/python/arcor2_arserver/objects_actions.py
- If server can't get collision model of the object, the object is disabled.
- Previously, this situation caused crash of the server.
=> fix(arcor2_arserver): handle missing collision model

src/python/arcor2/image.py, src/python/arcor2/tests/test_image.py, src/python/arcor2_arserver/rpc/scene.py
- arcor2/image.py
- `image_from_str` fixed
- minor improvements in other functions
- test added
- arcor2_arserver
- `calibration_cb` fixed (missing `image_from_str` added)
=> fix: image-related functions

src/python/arcor2_arserver/rpc/scene.py, src/python/arcor2_arserver_data/rpc/common.py, src/python/arcor2_calibration/calibration.py, src/python/arcor2_calibration/scripts/calibration.py, src/python/arcor2_calibration_data/__init__.py, src/python/arcor2_calibration_data/client.py
- Calibration service now has the method `PUT /markers/corners` which returns pixel coordinates of corners of the detected markers.
- ARServer has a new RPC `MarkersCorners` for this.
- Detecting corners is approx. three times faster than camera calibration (which uses the refinement method for higher accuracy).
=> feat: detect marker corners

src/python/arcor2_arserver/rpc/scene.py
- Callback of `MarkersCorners` RPC was missing `_cb` suffix.
- Because of this, it was not recognized as an RPC callback.
=> fix(arcor2_arserver): callback name fixed

src/python/arcor2/data/common.py, src/python/arcor2/parameter_plugins/base.py, src/python/arcor2/parameter_plugins/integer_enum.py, src/python/arcor2/parameter_plugins/relative_pose.py, src/python/arcor2_build/source/logic.py, src/python/arcor2_kinali/object_types/aubo.py
- `RelativePose` definition moved to `arcor2.data.common`.
- The main script now properly imports `RelativePose`, `Position` and `Orientation`.
=> fix: the RelativePose was not handled right

src/python/arcor2/flask.py
- It can be turned on by setting `ARCOR2_REST_API_DEBUG`.
=> feat: flask-based apps now don't log each API call by default

src/python/arcor2/helpers.py, src/python/arcor2/tests/test_helpers.py
- `is_valid_identifier` now behaves the same as `is_valid_type`.
- There is no convention (PascalCase vs snake_case) checking.
=> feat: tests for valid name/type now do not insist on format

src/python/arcor2/object_types/abstract.py, src/python/arcor2_arserver/robot.py, src/python/arcor2_arserver/rpc/robot.py, src/python/arcor2_arserver_data/events/robot.py, src/python/arcor2_arserver_data/rpc/robot.py, src/python/arcor2_fit_demo/object_types/abstract_dobot.py, src/python/arcor2_kinali/object_types/abstract_robot.py, src/python/arcor2_kinali/object_types/aubo.py, src/python/arcor2_kinali/object_types/simatic.py
- Robot RPCs updated (MoveToPose, MoveToJoints, MoveToActionPoint).
- Dobot robots will raise exception when `safe=True`.
- `Simatic` robot was missing `move_to_joints` (moved to `AbstractRobot`).
=> feat: standard robot API now has safe parameter

src/python/arcor2/clients/persistent_storage.py, src/python/arcor2/flask.py, src/python/arcor2_build/scripts/build.py
- A new method `PUT /project/import` to import the existing execution package.
- Import fails if data already exists and there is any difference.
- Import can be forced by setting the `overwrite` parameter.
- Build now returns response messages in JSON.
- Project service client: fix of `update_project_sources`.
=> feat(arcor2_build): import execution package to the Project service

src/python/arcor2_execution/scripts/execution.py
- Execution used SIGTERM instead of SIGINT.
- Because of this, the script was not stopped gracefully.
=> fix(arcor2_execution): script was stopped using wrong signal

src/python/arcor2_arserver/rpc/project.py
- Orientations/joints were not checked.
- Actions were checked but should not be.
=> fix(arcor2_arserver): checking of a name as a valid identifier

pants.toml, src/python/arcor2/cached.py, src/python/arcor2/data/__init__.py, src/python/arcor2/data/common.py, src/python/arcor2/data/tests/test_common.py, src/python/arcor2/object_types/abstract.py, src/python/arcor2/parameter_plugins/tests/test_boolean.py, src/python/arcor2/parameter_plugins/tests/test_double.py, src/python/arcor2/parameter_plugins/tests/test_image.py, src/python/arcor2/parameter_plugins/tests/test_integer.py, src/python/arcor2/parameter_plugins/tests/test_joints.py, src/python/arcor2/parameter_plugins/tests/test_pose.py, src/python/arcor2/parameter_plugins/tests/test_string.py, src/python/arcor2/parameter_plugins/tests/test_string_enum.py, src/python/arcor2/tests/test_logic.py, src/python/arcor2/tests/test_transformations.py, src/python/arcor2_arserver/execution.py, src/python/arcor2_arserver/rpc/project.py, src/python/arcor2_arserver/rpc/scene.py, src/python/arcor2_arserver/tests/test_openapi.py, src/python/arcor2_build/source/tests/test_logic.py, src/python/arcor2_kinali/examples/main_script_full_manual.py, src/python/arcor2_kinali/examples/main_script_with_resources.py, src/python/arcor2_kinali/object_types/abstract_robot.py
- Classes that rely on unique IDs (uuid) now generate those IDs on their own.
- If necessary, ID can be still provided.
- IDs are prefixed so developers can easily check the type of an object from its ID.
=> feat: uuid ids are now generated by a base class

3rdparty/constraints.txt, 3rdparty/requirements.txt, mypy.ini, src/python/arcor2/object_types/utils.py, src/python/arcor2/parameter_plugins/base.py, src/python/arcor2/parameter_plugins/boolean.py, src/python/arcor2/parameter_plugins/double.py, src/python/arcor2/parameter_plugins/image.py, src/python/arcor2/parameter_plugins/integer.py, src/python/arcor2/parameter_plugins/integer_enum.py, src/python/arcor2/parameter_plugins/joints.py, src/python/arcor2/parameter_plugins/pose.py, src/python/arcor2/parameter_plugins/relative_pose.py, src/python/arcor2/parameter_plugins/string.py, src/python/arcor2/source/__init__.py, src/python/arcor2/source/utils.py, src/python/arcor2_arserver/object_types/data.py, src/python/arcor2_arserver/object_types/source.py, src/python/arcor2_arserver/object_types/utils.py, src/python/arcor2_arserver/robot.py, src/python/arcor2_build/source/logic.py, src/python/arcor2_build/source/object_types.py, src/python/arcor2_build/source/utils.py
- `horast` was used as it does not discard comments.
- It seems to be abandoned now.
- Default `ast` seems to be 1000 times faster at parsing the code.
=> feat: get rid of horast

src/python/arcor2_kinali/CHANGELOG.md, src/python/arcor2_kinali/object_types/aubo.py
Changed the rest api call for `inverse_kinematics` for new [Robot](https://gitlab.com/kinalisoft/test-it-off/robot). Comitted as `fix` since there are not API breaking changes for arcor.
- ran formatter and linter, failed to run the typecheck and tests.
=> Change rest call for inverse kinematics

src/python/arcor2/resources.py
- This caused troubles with `RestHttpException` which requires a keyword-only argument.
- Added type annotations.
=> fix(arcor2/resources): removed useless creation of a new exception instance

src/python/arcor2/helpers.py, src/python/arcor2_arserver/decorators.py, src/python/arcor2_arserver/execution.py, src/python/arcor2_arserver/lock/lock.py, src/python/arcor2_arserver/objects_actions.py, src/python/arcor2_arserver/robot.py, src/python/arcor2_arserver/rpc/camera.py, src/python/arcor2_arserver/rpc/execution.py, src/python/arcor2_arserver/rpc/objects.py, src/python/arcor2_arserver/rpc/project.py, src/python/arcor2_arserver/rpc/robot.py, src/python/arcor2_arserver/rpc/scene.py, src/python/arcor2_arserver/scene.py
- Scene/project within RPC callbacks is now obtained using a method call.
- Context lock added to `CloseScene` RPC.
=> feat(arcor2_arserver): get rid of decorators and asserts

src/python/arcor2/helpers.py, src/python/arcor2/object_types/upload.py, src/python/arcor2/object_types/utils.py, src/python/arcor2_arserver/objects_actions.py, src/python/arcor2_build/scripts/build.py, src/python/arcor2_fit_demo/object_types/abstract_dobot.py, src/python/arcor2_fit_demo/object_types/fit_common_mixin.py, src/python/arcor2_fit_demo/object_types/kinect_azure.py, src/python/arcor2_fit_demo/scripts/kinect_calibration.py, src/python/arcor2_fit_demo/scripts/upload_objects.py
- ObjectTypes can now use mixins which are handled by ARServer and Build.
- It should be used like `class NewObjectType(MixinA, MixinB, Generic)`.
- E.g. the last ancestor should be something derived from `Generic`.
=> feat: support for multiple inheritance

src/python/arcor2_arserver/rpc/user.py, src/python/arcor2_arserver/user.py
- When a user was logged in and the device e.g. lost connection, it was not possible to log in again with the same user name for 20 seconds.
- ARServer now tries if the stored connection still works and if not, it allows re-use of the user name.
=> feat(arcor2_arserver): allow fast re-login after connection was broken

src/python/arcor2_kinali/object_types/statistic.py
Add `values_count` and `samples_count` filter fields for statistics endpoint
BREAKING CHANGE: drop endpoint for getting all names in group
=> feat(arcor2_kinali): update for Statistic Web API (0.6.0)

src/python/arcor2/data/object_type.py, src/python/arcor2/object_types/abstract.py, src/python/arcor2_arserver/object_types/utils.py, src/python/arcor2_arserver/objects_actions.py, src/python/arcor2_arserver/rpc/objects.py, src/python/arcor2_arserver/rpc/scene.py, src/python/arcor2_arserver/tests/test_objects.py, src/python/arcor2_arserver_data/rpc/scene.py
- `VirtualCollisionObject` is meant as a base for 'dumb' collision objects, with primitive models.
- There is a new RPC `AddVirtualCollisionObjectToScene` which creates a new ObjectType and adds its instance to a scene.
- In the simplest case, each collision object will have its own ObjectType (but it is also possible to add more instances as with other types).
- When the last instance of virtual object is removed, ARServer also removes the ObjectType automatically.
=> feat: virtual collision objects

src/python/arcor2_arserver/rpc/scene.py, src/python/arcor2_arserver/tests/test_objects.py, src/python/arcor2_arserver_data/objects.py
- `source` was empty when putting OT on the Project service.
=> fix(arcor2_arserver): adding virtual collision objects

src/python/arcor2/data/events.py, src/python/arcor2_arserver/tests/test_project_execution.py, src/python/arcor2_execution_rest_proxy/scripts/execution_rest_proxy.py, src/python/arcor2_runtime/action.py, src/python/arcor2_runtime/tests/test_action.py
This is a merge request for AP visualization, as we have discussed.
Basically I have changed `ActionStateBefore` event scheme, then I have updated runtime `@action` decorator to get AP ids from arguments. Due to this change the `ActionStateBefore` will be dispatched for each action (with or without id or any pose/joints in arguments). This event will be than handled by rest proxy. 
At rest proxy I have added 2 global variables to hold last action state - one for `ActionStateBefore.Data` and another for `ActionStateAfter.Data`, just like you hold `package_state` for example. `ActionStateAfter` will be unset once `ActionStateBefore` is met (at this moment `ActionStateAfter` already belongs to previous action), however `ActionStateBefore` will never be unsettled once set. We have discussed …
=> Visualization action points

.github/workflows/pants.yaml, 3rdparty/BUILD, 3rdparty/constraints.txt, 3rdparty/requirements.txt, build-support/install_kinect_prerequisites.sh, docker/Dockerfile-kinect-azure, docker/build.sh, src/python/arcor2_kinect_azure/README.md
- No need to install kinect sdk.
- Docker image is now based on slim buster as other images.
- Please note: the current version of `pyk4a-bundle` has some issues and does not work.
- ...however, this simplifies work with our repo, so it's integrated anyway.
=> build(kinect): use bundled pyk4a

3rdparty/BUILD, 3rdparty/constraints.txt, 3rdparty/requirements.txt, src/python/arcor2/clients/project_service.py
- `dateutil` is now used to parse `datetime` from iso format.
- There was a `ValueError` for more than 6 decimal places.
=> fix(arcor2): project service client

src/python/arcor2_build/scripts/build.py, src/python/arcor2_mocks/scripts/mock_project.py
- For testing purposes, there used to be shuffling of scene objects to make sure that the order does not matter.
- This probably fits better to a mock of the Project service than into the Build service.
- Moreover, the shuffling of stuff in a project was added.
=> refactor: shuffling of scene objects moved from Build to Project mock
