- arcor2/data/rpc/robot.py
- arcor2/server/rpc/robot.py
> ARServer: new RPC to get robot joints, effector pose

- arcor2/data/robot.py
- arcor2/nodes/__init__.py
- arcor2/nodes/server.py
- arcor2/object_types/robot.py
- arcor2/parameter_plugins/integer.py
- arcor2/server/globals.py
- arcor2/server/objects_services_actions.py
- arcor2/server/robot.py
- arcor2/server/rpc/scene.py
- arcor2/server/settings.py
Robot URDF package is copied to the ARCOR2_DATA_PATH. Http server (e.g. "python -m http.server 6780") is started in this directory and enables AREditor to download this data. Package filename is added to robot metadata.
> Robot Model (URDF) support

- .github/workflows/publish-pre-release.yml
> Publish pre-release only when pushing to the robofit/devel

- src/python/arcor2_arserver/scene.py
> fix: Call scene/stop before attempt to start the scene

- src/python/arcor2/clients/aio_persistent_storage.py
- src/python/arcor2/clients/persistent_storage.py
- src/python/arcor2/clients/scene_service.py
- src/python/arcor2/data/object_type.py
- src/python/arcor2/rest.py
- src/python/arcor2_arserver/execution.py
- src/python/arcor2_calibration_data/client.py
- src/python/arcor2_kinali/object_types/abstract_robot.py
- src/python/arcor2_kinali/object_types/abstract_with_pose.py
- src/python/arcor2_kinali/object_types/barcode.py
- src/python/arcor2_kinali/object_types/interaction.py
- src/python/arcor2_kinali/object_types/kinali_robot.py
- src/python/arcor2_kinali/object_types/search.py
- src/python/arcor2_kinali/object_types/statistic.py
- src/python/arcor2_kinali/scripts/example_main.py
BREAKING CHANGE: now there is only one method 'call' which takes http method as an argument
> feat: rest module rewritten

- src/python/arcor2/helpers.py
- src/python/arcor2/logging.py
- src/python/arcor2/rest.py
- src/python/arcor2_arserver/globals.py
- src/python/arcor2_arserver_data/client.py
- src/python/arcor2_build/scripts/build.py
- src/python/arcor2_calibration/scripts/calibration.py
- src/python/arcor2_execution/scripts/execution.py
Log format was also changed slightly.
> refactor: loggers are now created using functions from logging module

- docker/Dockerfile-arserver
- docker/Dockerfile-dist-base
- Dockerfile-arserver: ~/project is not needed.
- Dockerfile-dist-base: turn on optimization by setting env. variable (removes asserts).
> build(docker): docker files updated

- 3rdparty/constraints.txt
- 3rdparty/requirements.txt
- src/python/arcor2_kinali/object_types/kinali_robot.py
Workaround in kinali_robot not needed anymore.
> build: asttokens version updated

- pants.toml
- src/python/arcor2/resources.py
- Fixed type annotation of `IntResources` context manager.
- Added some missing `__init__.py` files causing mypy to complain.
> build: flake8/mypy version updated

- src/python/arcor2/logic.py
- src/python/arcor2/tests/test_logic.py
- It wasn't working properly with branched logic.
> fix(arcor2): logic loop detection

- src/python/arcor2/action.py
- Because of this, pause/resume was broken.
> fix(arcor2): action decorator was missing call to handle_action

- src/python/arcor2_calibration/scripts/calibration.py
- src/python/arcor2_kinect_azure/scripts/kinect_azure.py
- Activated by `--mock` argument.
> feat: mock mode for Calibration/KinectAzure

- docker/fit-demo/docker-compose.yml
- docker/kinali-demo/docker-compose.yml
- src/python/arcor2/clients/scene_service.py
- src/python/arcor2_kinali/object_types/abstract_robot.py
- src/python/arcor2_kinali/object_types/aubo.py
- src/python/arcor2_kinali/object_types/search.py
- src/python/arcor2_kinali/object_types/simatic.py
- src/python/arcor2_mocks/scripts/scene.py
- Robot 0.9.0
- Scene 0.4.0
- Search 0.7.0
- Barcode 0.4.0
> feat: clients for Kinali services updated

- src/python/arcor2_arserver/scene.py
- `pose` was `None` in some cases.
> fix(arcor2_arserver): update_scene_object_pose

- src/python/arcor2/resources.py
- When started, the main script attempted to stop the scene without testing if it is running.
> fix(arcor2): main script now stops the scene properly

- src/python/arcor2/ws_server.py
- Max. duration could be configured using `ARCOR2_MAX_RPC_DURATION` environment variable, default is 0.1s.
> feat(arcor2): ws_server now logs too long callbacks

- 3rdparty/constraints.txt
- 3rdparty/requirements.txt
- mypy.ini
- pants.toml
- src/python/arcor2/data/camera.py
- src/python/arcor2/data/common.py
- src/python/arcor2/image.py
- src/python/arcor2_calibration/calibration.py
- src/python/arcor2_calibration/robot.py
- src/python/arcor2_fit_demo/scripts/BUILD
- src/python/arcor2_kinect_azure/kinect_azure.py
- src/python/arcor2_kinect_azure/scripts/BUILD
- src/python/arcor2_kinect_azure/scripts/kinect_viewer.py
- Plus there is some typing-related stuff fixed.
> build: numpy version updated

- src/python/arcor2_arserver/rpc/project.py
- src/python/arcor2_build/source/logic.py
- src/python/arcor2_build/source/object_types.py
- src/python/arcor2_build/source/tests/test_logic.py
- src/python/arcor2_build/source/utils.py
- There was already some level of support in ARServer.
- Now also Build can handle constants.
- So far, only basic types are supported.
- Eventually, constants should be handled by some plugin(s).
> feat: finished support for project constants

- src/python/arcor2_fit_demo/tests/BUILD
- src/python/arcor2_fit_demo/tests/test_with_arserver.py
- src/python/arcor2_kinali/tests/BUILD
- src/python/arcor2_kinali/tests/test_with_arserver.py
- src/python/arcor2_mocks/scripts/mock_project.py
- Integration tests checking whether OTs are ok for ARServer.
- Methods to store/get mesh files were added to the mock Project.
> test: check whether ARServer accepts ObjectTypes

- docker/README.md
- docker/fit-demo/docker-compose.yml
- docker/kinali-demo/docker-compose.yml
- `XYZ_VERSION` env. vars. were removed.
- The services versions will be updated on each release.
> chore(docker): updated services versions

- src/python/arcor2/rest.py
- src/python/arcor2_kinali/examples/main_script_full_manual.py
- An example was added into arcor2_kinali/examples.
> feat(arcor2): a new exception type RestHttpException for getting HTTP error codes

- src/python/arcor2_arserver/robot.py
- src/python/arcor2_fit_demo/object_types/abstract_dobot.py
- src/python/arcor2_fit_demo/object_types/tests/test_abstract_dobot.py
- src/python/arcor2_fit_demo/object_types/tests/test_dobot_m1.py
- src/python/arcor2_fit_demo/object_types/tests/test_dobot_magician.py
- src/python/arcor2_fit_demo/tests/test_with_arserver.py
- src/python/arcor2_kinali/object_types/simatic.py
- src/python/arcor2_kinali/object_types/tests/test_abstract_robot.py
- src/python/arcor2_kinali/object_types/tests/test_aubo.py
- src/python/arcor2_kinali/tests/test_with_arserver.py
- Fixed signatures of some robot methods.
- Robot features are now checked using tests.
- Improved logging in ARServer.
> fix: robot features

- src/python/arcor2/CHANGELOG.md
- src/python/arcor2_arserver/CHANGELOG.md
- src/python/arcor2_build/CHANGELOG.md
- src/python/arcor2_dobot/CHANGELOG.md
- src/python/arcor2_dobot/dobot.py
- src/python/arcor2_dobot/m1.py
- src/python/arcor2_execution/CHANGELOG.md
- src/python/arcor2_fit_demo/CHANGELOG.md
- src/python/arcor2_kinali/CHANGELOG.md
- Release dates added to readme's
> feat(arcor2_dobot): fix of dobot joints and eef position

- README.md
* fixed release dates of some older releases
> docs: added new release of arcor2_dobot

- src/python/arcor2/data/common.py
- src/python/arcor2/transformations.py
- src/python/arcor2_arserver/robot.py
- src/python/arcor2_arserver/rpc/robot.py
- src/python/arcor2_arserver_data/rpc/robot.py
- src/python/arcor2_calibration/calibration.py
- src/python/arcor2_dobot/magician.py
- New RPC `SetEefPerpendicularToWorld`.
- New RPC `StepRobotEef`.
> feat(arcor2_arserver): new robot-related functionalities

- src/python/arcor2/data/common.py
- src/python/arcor2/tests/test_transformations.py
- src/python/arcor2/transformations.py
- src/python/arcor2_arserver/rpc/scene.py
- src/python/arcor2_calibration/robot.py
- Code simplified, duplication reduced.
> feat: pose transformation code improvements

- 3rdparty/constraints.txt
- 3rdparty/requirements.txt
- src/python/arcor2/data/__init__.py
- This is to deal with a bug in dataclasses_jsonschema.
> feat: use monkey patching instead of custom released version

- src/python/arcor2_kinali/CHANGELOG.md
- src/python/arcor2_kinali/object_types/abstract_robot.py
Updated API of abstract robot to reflect Robot 0.10.0 [changes](https://gitlab.com/kinalisoft/test-it-off/robot).
> Change grip method to return bool

- src/python/arcor2_arserver/helpers.py
- src/python/arcor2_arserver/lock/lock.py
- src/python/arcor2_arserver/lock/notifications.py
- src/python/arcor2_arserver/lock/structures.py
- src/python/arcor2_arserver/robot.py
- src/python/arcor2_arserver/rpc/project.py
- src/python/arcor2_arserver/rpc/scene.py
- src/python/arcor2_arserver/rpc/user.py
- fixed bug with stepping robot
- fixed possible bug with creating new scene
- added check if any object locked in UI when UI tries to get whole lock struct
> feat(arcor2_arserver): lock bugfixes and improvements

- src/python/arcor2_arserver/decorators.py
- src/python/arcor2_arserver/helpers.py
- src/python/arcor2_arserver/lock/README.md
- src/python/arcor2_arserver/lock/lock.py
- src/python/arcor2_arserver/lock/structures.py
- src/python/arcor2_arserver/robot.py
- src/python/arcor2_arserver/rpc/lock.py
- src/python/arcor2_arserver/rpc/project.py
- src/python/arcor2_arserver/rpc/robot.py
- src/python/arcor2_arserver/rpc/scene.py
- src/python/arcor2_arserver/tests/test_lock.py
- bugfixes with lock structure and RPCs
- unified locking exception message
- added readme.md for lock package
> feat: updated lock structure test, bugfixes

- src/python/arcor2_arserver/helpers.py
- src/python/arcor2_arserver/robot.py
- src/python/arcor2_arserver/rpc/objects.py
- src/python/arcor2_arserver/rpc/project.py
- src/python/arcor2_arserver/rpc/robot.py
- src/python/arcor2_arserver/rpc/scene.py
- src/python/arcor2_arserver_data/rpc/project.py
- New RPC `AddApUsingRobot`.
- Robot-related functions optimized.
> feat: new RPC to add AP using a robot

- src/python/arcor2_arserver/clients/persistent_storage.py
- src/python/arcor2_arserver/objects_actions.py
- Functions to get scene/project/OT IDs as a set.
- Reduced code duplication.
- Remove outdated items from the cache.
> feat(arcor2_arserver): improved project service client

- src/python/arcor2/cached.py
- src/python/arcor2_arserver/helpers.py
- src/python/arcor2_arserver/lock/README.md
- src/python/arcor2_arserver/lock/lock.py
- src/python/arcor2_arserver/lock/notifications.py
- src/python/arcor2_arserver/lock/structures.py
- src/python/arcor2_arserver/rpc/project.py
- src/python/arcor2_arserver/rpc/robot.py
- src/python/arcor2_arserver/tests/test_lock.py
- removed redundant lock structure
- fixed bugs with lock events
- added some secure checks
- fixed bugs related to locking
> fix(arcor2_arserver): fixed lots of bugs

- src/python/arcor2/data/common.py
- src/python/arcor2/image.py
- src/python/arcor2/json.py
- src/python/arcor2/object_types/utils.py
- src/python/arcor2/parameter_plugins/base.py
- src/python/arcor2/parameter_plugins/integer_enum.py
- src/python/arcor2/parameter_plugins/list.py
- src/python/arcor2/parameter_plugins/pose.py
- src/python/arcor2/resources.py
- src/python/arcor2/rest.py
- src/python/arcor2_arserver/rpc/project.py
- src/python/arcor2_arserver_data/client.py
- src/python/arcor2_build/scripts/build.py
- src/python/arcor2_build/source/logic.py
- src/python/arcor2_execution/scripts/execution.py
- Wraps the standard json module.
- ...it might be easier to replace it in the future.
- Provides type annotations.
- Raises a custom exception based on `Arcor2Exception`.
> feat(arcor2/json): custom json module

- src/python/arcor2_arserver/decorators.py
- src/python/arcor2_arserver/globals.py
- src/python/arcor2_arserver/lock/README.md
- src/python/arcor2_arserver/lock/lock.py
- src/python/arcor2_arserver/lock/structures.py
- src/python/arcor2_arserver/robot.py
- src/python/arcor2_arserver/rpc/robot.py
- src/python/arcor2_arserver/tests/test_lock.py
- lock test broken into smaller cases
- added documentation to lock
- bugfixes with locking robot
- updated retry logging
> fix(arcor2_arserver): bugfixes, test updates, added documentation

- src/python/arcor2/cached.py
- src/python/arcor2_arserver/clients/persistent_storage.py
- src/python/arcor2_arserver/rpc/project.py
- src/python/arcor2_arserver/rpc/scene.py
- Code of the `cached` module was slightly refactored.
- Fixes a bug where it was possible to create a project from an unsaved scene.
> feat: it is now possible to save empty scene or project

- src/python/arcor2/cached.py
- Due to bad exception handling, inconsistency occurred.
- Two dicts merged into one - to prevent such errors and for better performance.
- Handling of exceptions improved.
> fix(arcor2/cached): double call of _remove_child in remove_action

- src/python/arcor2_arserver/project.py
- It should be possible to create a new project from the online scene.
> fix(arcor2_arserver): invalid assert removed

- src/python/arcor2_arserver/project.py
- Only scene objects were considered as possible parents.
- Invalid joints were considered to be a problem.
> fix(arcor2_arserver): project problems

- src/python/arcor2_arserver/rpc/project.py
- Some basic checks are now done before attempting to lock anything.
> feat(arcor2_arserver): update action point parent

- src/python/arcor2/object_types/abstract.py
- src/python/arcor2/test_objects/dummy_multiarm_robot.py
- src/python/arcor2_arserver/robot.py
- src/python/arcor2_arserver/rpc/project.py
- `check_if_ready_to_move` overwritten in `MultiArmRobot`.
- A robot won't be ready to move if one of the arms is in HTM.
- `DummyMultiArmRobot` improved.
> fix: multi arm robot related fixes

- src/python/arcor2/flask.py
- src/python/arcor2_build/scripts/build.py
- src/python/arcor2_calibration/scripts/calibration.py
- src/python/arcor2_dobot/scripts/dobot.py
- src/python/arcor2_execution_rest_proxy/scripts/execution_rest_proxy.py
- src/python/arcor2_kinect_azure/scripts/kinect_azure.py
- src/python/arcor2_mocks/scripts/mock_project.py
- src/python/arcor2_mocks/scripts/mock_scene.py
- For most of the REST services...
> feat: service and API versions will be the same

- docker/fit-demo/docker-compose.yml
- docker/start-kinect-azure.sh
- Version of the service updated.
- Removed `--mock` from the script.
> chore(docker): kinect

- .dockerignore
- docker/Dockerfile-base
- docker/Dockerfile-dist-base
- docker/build.sh
- automaticaly pull newest base image for our base and dist-base images
- add some pants-related folders to the dockerignore file to shrink docker build context
> chore(docker): build enhancements

- docker/fit-demo/README.md
- docker/fit-demo/docker-compose.lab.yml
- docker/fit-demo/docker-compose.yml
- Override for the lab added.
- Dobot services renamed.
- arcor2_fit_demo image added (uploads objects).
> chore(docker): fit-demo

- compose-files/fit-demo/docker-compose.yml
- src/python/arcor2_arserver/tests/testutils.py
- src/python/arcor2_build/CHANGELOG.md
- src/python/arcor2_build/scripts/build.py
- src/python/arcor2_calibration/CHANGELOG.md
- src/python/arcor2_calibration/scripts/calibration.py
- src/python/arcor2_dobot/CHANGELOG.md
- src/python/arcor2_dobot/scripts/dobot.py
- src/python/arcor2_execution_rest_proxy/CHANGELOG.md
- src/python/arcor2_execution_rest_proxy/scripts/execution_rest_proxy.py
- src/python/arcor2_mocks/CHANGELOG.md
- src/python/arcor2_mocks/scripts/mock_asset.py
- src/python/arcor2_mocks/scripts/mock_project.py
- src/python/arcor2_scene/CHANGELOG.md
- src/python/arcor2_scene/scripts/scene.py
- End-point path synchronized with Kinali services.
- `fit-demo` updated to use Asset 0.6.0 and Project 0.23.0.
> feat: health check

- compose-files/fit-demo/docker-compose.yml
- src/python/arcor2/CHANGELOG.md
- src/python/arcor2/clients/scene_service.py
- src/python/arcor2/data/object_type.py
- src/python/arcor2_arserver/objects_actions.py
- src/python/arcor2_arserver/tests/test_object_aiming.py
- `data_id` changed to `asset_id` in `Mesh`.
> feat: compatibility with Project 1.0.0-rc.4

- compose-files/fit-demo/nginx.conf
- Make the path the same as on the Asset service.
> chore: update nginx configuration
